### ISSUE TITLE
Bug - Use only one vm

### ISSUE THREAD

**Issue by zic04** [davidande/FSRM-ANTICRYPTO#11]
Hello,
I encounter problem with Group Policy Object (GPO) doesnt work. :

One Vm with :  
- AD
- FSRM
- DATA (C - D)
- RDWEB
- RD gateway

Is it possible to exclude c: from the script ?

**Comment by kl3sk** [comment]
@zic04 Does `share_to_accept.txt` is usable for that ?

**Comment by zic04** [comment]
@kl3sk thank you but for the link does not work. 

"C:\Windows\SYSVOL\domain\scripts"

Works for : 

C:\
C:\Windows
C:\share
C:\Windows\SYSVOL\sysvol

**Comment by kl3sk** [comment]
Just for tests. If only `C:\Windows\SYSVOL\domain\scripts` is in the file. Does it works ?

**Comment by davidande** [comment]
I got the same Issue. But You must know that on all administrative shares, the filtering is in passive mode (It does not block anything, only display in the event log.
But I have found something.
if You only launch: Get-WmiObject Win32_Share | Select Name,Path,Type | Where-Object { $_.Type -match  '0|2147483648' } | Select -ExpandProperty Path | Select -Unique
You will list the all shares. for me the script directory is 
C:\Windows\SYSVOL\MY-DOMAIN.local\SCRIPTS
but on the log I see
![image](https://user-images.githubusercontent.com/22703387/60094028-4061bf80-974b-11e9-8a69-574affd757e5.png)

So If you add: C:\Windows\SYSVOL\sysvol\MY-DOMAIN.local\SCRIPTS to the share_to_accept.txt it should work.
is It?

**Comment by zic04** [comment]
after checking your solution works,
Thank you,

**Comment by davidande** [comment]
So You don't need to add the administrative shares in the share_to_accept.txt.
Just go inside the script and set the value of delpassive to 1
![image](https://user-images.githubusercontent.com/22703387/60100711-9a1db600-975a-11e9-8512-f5b380616ba7.png)

**Comment by davidande** [comment]
You can test it and come back to me if it works also for You

**Comment by zic04** [comment]
I just tried and the solution works perfectly

**Comment by zic04** [comment]
The first solution with "share to accept" : works 

The second solution delpassive:1 : encounter the problem Group Policy Object (GPO) 
- (the specified server can not perform the requested operation)

**Comment by davidande** [comment]
I Thinks it's linked to your GPO restrictions

**Comment by zic04** [comment]
Second solution :
 I think the script modifies the right of access. To fix i run the powershel command `dcgpofix /ignoreschema /target:Domain`
