### ISSUE TITLE
*.locked entry in ext_to_accept.txt not working

### ISSUE THREAD

**Issue by hanshegeman** [davidande/FSRM-ANTICRYPTO#12]
I want to exclude the file pwruser.ini.locked and put it in the ext_to_accept.txt file, but it is still blocked. Tried even *.locked but these files are also blocked. Tried *.backup and this one is not blocked. The ext_to_accept.txt file works but not the *.locked entry.

**Comment by davidande** [comment]
can You try *.ini.locked ?

**Comment by hanshegeman** [comment]
Tried it but doesn't work also.
