### ISSUE TITLE
New-FsrmFileScreen : 0x80045315, The specified volume is unsupported

### ISSUE THREAD

**Issue by Julien-nl** [davidande/FSRM-ANTICRYPTO#15]
I am trying to run the script on our VEEAM server to protect our backups as well.
however the error keeps showing 

`New-FsrmFileScreen : 0x80045315, The specified volume is unsupported`
C Partition is working file.
Server 2019 Datacenter
Disk is REFS

**Comment by davidande** [comment]
Hello,
I think that the problem comes from the REFS disk. 
REFS does not support yet FSRM
https://techcommunity.microsoft.com/t5/windows-server-insiders/when-will-fsrm-quotas-file-screens-be-supported-on-refs/m-p/95919

Best Regards
David

**Comment by Julien-nl** [comment]
Thanks David,
yes the error comes from F: Disk which is FSRM.
i hope it will be supported soon to protect the backup server too

**Comment by davidande** [comment]
if it's a VM, try to reboot it

**Comment by Julien-nl** [comment]
i have rebooted it like twice before i post the error. but i'll reboot it again.
i have rebooted for the 5th time and now it seems to work.

**Comment by Julien-nl** [comment]
is it possible to use it on Exchange 2013/2016/2019 ?

**Comment by davidande** [comment]
No

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Julien-nl** [comment]
it would block the exchange database? i've tried already on the lab but it seems to works.
