### ISSUE TITLE
ext_to_accept.txt pas pris en compte

### ISSUE THREAD

**Issue by Didfour** [davidande/FSRM-ANTICRYPTO#16]
Bonjour David

J'avais un vieux script de ce programme sur mon serveur 2012 R2. J'ai donc supprimé la configuration existante de FSRM et installé votre script.

J'effectue les maj toutes les heures via une tache planifiée qui exécute le batch suivant (La maj fonctionne bien)
Powershell.exe -noprofile -ExecutionPolicy Unrestricted -File C:\FSRMNOCRYPTO\FSRM_NOCRYPTO_2012_to_2022.ps1

Le script bloque bien les extensions sauf qu'il ne prend pas les extensions que je veux autoriser dans "ext_to_accept.txt" en l'occurrence l'extension *.cry

Sauriez-vous pourquoi ?

# PUT HERE THE LIST OF ALL EXTENSIONS PRESENT IN THE BLOCKED LIST, YOU WANT TO BE ACCEPTED
# IN THE CASE A PROGRAM USE AN EXTENSION THAT IS LISTED AND FORBIDDEN.
# ONE EXTENSION PER LINE.
# example
# *.jse
# *.1
*.cry

Didier

**Comment by davidande** [comment]
Si je comprends bien, vous souhaitez autoriser l'écriture de fichier avec l'extension *.cry?
Vous devez avoir ces trois autres fichiers présent dans votre répertoire.
share_to_accept.txt, ext_to_accept.txt  et ext_to_exclude.txt.
refaite le test en étant certains que ces fichiers sont présents
