### ISSUE TITLE
experiant list not updating

### ISSUE THREAD

**Issue by jf40541** [davidande/FSRM-ANTICRYPTO#17]
David,

Can you possibly update your script or possibly post the required script changes to use a list forked from the fsrm.experiant.ca list? It seems this forked version of the list is currently being updated https://github.com/rivir/CryptoBlocker/raw/master/list. 

Any help appreciated.

Regards,
Jeff

**Comment by davidande** [comment]
Hello,
Could You test this?
starting line 140
{
# $jsonStr = Invoke-WebRequest -Uri $url -UseBasicParsing
# $monitoredExtensions = @(ConvertFrom-Json20($jsonStr) | % { $_.filters })
$monitoredExtensions = $webClient.DownloadString("https://github.com/rivir/CryptoBlocker/raw/master/list")
}

thanks

**Comment by gizmo21** [comment]
This raw of an other fork is the most up-to-date atm:
https://raw.githubusercontent.com/DFFspace/CryptoBlocker/master/list.txt

But more community support to add new extensions is needed(!) and the list is updated via posting new extensions as "Issues" here:
https://github.com/DFFspace/CryptoBlocker/issues?q=is%3Aissue

**Comment by davidande** [comment]
Thakns @gizmo21 for the info.
updated the script.
Could You please check if everuthing works?

**Comment by davidande** [comment]
We validate the new list is working great.
Next step will be to donwload multi extension list sources and merge it.
close this issue
