### ISSUE TITLE
Have you seen this?  New-fsrmaction : Not Found

### ISSUE THREAD

**Issue by netfidelis2017** [davidande/FSRM-ANTICRYPTO#6]
![image](https://user-images.githubusercontent.com/34890449/35048643-b070d4c8-fb6b-11e7-92f8-c344a7586e22.png)

Hopefully you can see the pasted graphic

**Comment by davidande** [comment]
hello,
Yes I know this bug.
It's caused by Internet Explorer.
just launch internet explorer on the server and choose your security profile (what ever you want).
The script should run ok after

**Comment by netfidelis2017** [comment]
That didn't seem to do it, I wander if a reboot is required after opening IE?  or some security setting in particular

**Comment by netfidelis2017** [comment]
I'm running on 2012R2 for your info.  It's odd because I have it on lots of other 2012 R2 with no issues, but this one server seems to be picky in some way

**Comment by netfidelis2017** [comment]
Also, on a Hyper-V host

**Comment by davidande** [comment]
we had alo fix this rebooting few times.

**Comment by netfidelis2017** [comment]
2 more reboots of the server fixed the issue with the 2016 version.  I was getting the same type of error for the 2008 version, like it couldn't find the filescrn.exe to run the commandlet.  I added c:\windows\system32\ in front of the filescrn.exe everywhere in the script and it ran fine after that.  Just for your info.  

THanks for the help, script works great!
