### ISSUE TITLE
Remote extension list Offline - Quit

### ISSUE THREAD

**Issue by akaakroma** [davidande/FSRM-ANTICRYPTO#8]
Hello, I followed the insctructions, IE also working, but Im having this message : "Remote extension list Offline - Quit"

When I access the url via IE it is trying to download instead of showing extensions

W2016 standard

Thank you

**Comment by davidande** [comment]
Do You have Exchange on your server?

**Comment by akaakroma** [comment]
No exchange

Richard MASSONNET

**Comment by davidande** [comment]
ok,
so just open powershell ISE in admin mode, open the script and try.
You can also try to test inside powershell ISE to rich the extension list:

$url = "https://fsrm.experiant.ca/api/v1/get"
$wkdir = "C:\FSRMNOCRYPTO"
Invoke-WebRequest $url -OutFile $wkdir\test.txt

**Comment by akaakroma** [comment]
Same result :
![image](https://user-images.githubusercontent.com/42836287/44900938-53138f80-ad06-11e8-8b26-e8dea242c08c.png)

**Comment by davidande** [comment]
![image](https://user-images.githubusercontent.com/22703387/44902761-1ac28000-ad0b-11e8-879b-421ada752915.png)

Il y a un souci dans le chemin

**Comment by davidande** [comment]
Par ailleurs ça fonctionne parès, pouvez vous tester l'autre script, celui qui est en beta.
merci

**Comment by akaakroma** [comment]
Ah yes !

Comment est-ce possible de ne pas se rendre compte de çà parfois ! c'est bien passé, les extensions sont ajoutées, je dois cependant les activer manuellement dans filtre de fichiers et modèles de fichiers, peut -être parce que j'avais déjà passé un précédent autre script. Si vous pouviez supprimer la dernière image que vous aviez corrigé pour enlever le nom de l'AD, 

Merci pour votre suivi

Bonne journée

**Comment by davidande** [comment]
pour les filtrage en actif, il n'est pas possible de le faire sur les partages administratifs (restriction Windows).
Comprenez que ce script protège les partages et non tous les fichiers.

Pour avoir une vue plus facile des erreurs, je vous conseille de lancer le script dans powershell ISE. Si vous souhaitez relancer le script manuellement plusieurs fois, il suffit avant chaque execution de modifier le contenu du fichier extensions.old. (sinon vous aurez un message comme quoi la liste d'extensions est à jour.

**Comment by davidande** [comment]
Par ailleurs, je vous conseille la version BETA du script qui permet de supprimer la protection sur les partages administratif.
