### ISSUE TITLE
ext_to_accept.txt doesnt work

### ISSUE THREAD

**Issue by markrholloway** [davidande/FSRM-ANTICRYPTO#9]
Hi,

The code doesn't update the file group to remove extensions when adding file extensions to the ext_to_accept.txt file. I am using the most up to date PowerShell code on Windows Server 2012 R2.

Please can you assist?

Thanks,

Mark

**Comment by davidande** [comment]
Hello,
Just checked on servers and it seems to work.
Could You please copy and paste here your ext_to_accept.txt plz?

**Comment by markrholloway** [comment]
Hi,

Thanks for your response.
Attached is ext_to_accept.txt

Mark
________________________________

**Comment by davidande** [comment]
It's correct.
so when You try to write a file with *.enc in a share (that is protected), it's forbidden?

**Comment by markrholloway** [comment]
Hi,

That is correct. When I save a file with either *.enc or *.one, the File Screen Template blocks the file from being saved to the share. I have checked the File group created by the script via File Server Resource Monitor and the extensions are still visible in the File group even though the PowerShell prints out they are being excluded...

[cid:ddf19487-2063-4bd2-a3cc-478ecf9e7103]

Thanks,

Mark
________________________________

**Comment by davidande** [comment]
can You try the new version of the script plz and tell me if it works for You

**Comment by markrholloway** [comment]
Hi David,

Script now works perfectly. Many thanks for your quick response and fix. Great piece of code.

Thanks,

Mark
________________________________

**Comment by davidande** [comment]
Ok that's good :-)
Thanks for your support.
By the way, i just did an update of the script because of the same problem found in share-to-accept function.
